sudo: required
dist: trusty
os:
    - linux
language: minimal
env:
  global:
  matrix:
    - target_v=windows
    - target_v=linux_daemon
    - target_v=linux_wallet
before_install:
install:
before_script:
script:
    - if [[ "$target_v" == "linux_daemon" ]]; then python ci_scripts/test_linux-daemon.py        ; fi
    - if [[ "$target_v" == "linux_wallet" ]]; then python ci_scripts/test_linux-gui_wallet.py    ; fi
    - if [[ "$target_v" == "windows" ]];      then python ci_scripts/test_win32-gui_wallet.py    ; fi


after_script:
    - echo "Done"
    
notifications:
  email:
    recipients:
      - info@nebl.io
